go_import_path: github.com/fahim/go-http-test
language: go
go:
  - 1.5
before_install:
  - go get github.com/fahim/go-http-test/api

script:
  - go build
  - ls -la
  - ./go-http-test &
  - go test -v api/api_test.go